repos:
  - repo: https://github.com/python-poetry/poetry.git
    rev: 2.0.0
    hooks:
      #- id: poetry-check
      - id: poetry-install
        stages: [post-checkout, post-merge]
        always_run: true
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
        args: [--maxkb=10240]
      - id: check-case-conflict
      - id: check-docstring-first
        exclude: (__init__|io).py
      - id: check-json
      - id: check-toml
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: trailing-whitespace
        exclude: .pdf|.svg|.graphml
      - id: pretty-format-json
        exclude: .ipynb
        args: [--autofix]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.6
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix, --config=pyproject.toml]
      - id: ruff-format
